version: 2

sources: 
    - name: raw
      schema: gz_raw_data      
      description: Raw gz data from Le Wagon
      tables: 
        - name: sales 
          identifier: raw_gz_sales
          description: sales of Greenweez, one row per product_id found in each orders_id
          loaded_at_field: "CAST(date_date AS TIMESTAMP)"
          freshness:
            warn_after: {count: 90, period: day}
          columns:
            - name: date_date
              description: date of purchase
            - name: orders_id
              description: unique identifier for one order
            - name: products_id
              description: identifier for each product within an order
            - name: revenue
              description: revenue raised on each product
            - name: quantity
              description: number of each product purchased within this order
          tests:
            - unique:
                column_name: "(orders_id || '-' || pdt_id)"
        - name: product
          identifier: raw_gz_product
          description: products_id stored alongside purchase price for each of these products
          columns:
            - name: products_id
              description: unique identifier of each product, primary key
              tests:
                - unique  
                - not_null         
            - name: purchase_price
              description: price paid to acquire each individual product 
        - name: ship
          identifier: raw_gz_ship
          description: details of shipping fee(income) and log and ship costs against each orders_id
          columns:
            - name: orders_id
              description: unique identifier of each order, primary key
              tests:
                - unique
                - not_null
            - name: shipping_fee
              description: income paid for shipping
            - name: logCost
              description: logisitics costs in shipping order
            - name: ship_cost
              description: cost of shipping order
        - name: adwords
          identifier: raw_gz_adwords
          description: data from adwords for gz
          columns:
           - name: date_date
             description: date details
             tests:
                - not_null
           - name: paid_source
             description: source of ads
           - name: campaign_key
             description: key of specific campaign ad is associated with
             tests:
                - not_null
           - name: campgn_name
             description: name of specific campaign, note column name changed in staging
           - name: ads_cost
             description: cost of this ad, not cast as float64 in staging
           - name: impression
             description: number of impressions for this ad
           - name: click
             description: number of clicks from this ad
          tests:
           - unique:
              column_name: "(date_date || '-' || campaign_key)"
        - name: bing
          identifier: raw_gz_bing
          description: data from bing for gz
          columns:
           - name: date_date
             description: date details
             tests:
                - not_null
           - name: paid_source
             description: source of ads
           - name: campaign_key
             description: key of specific campaign ad is associated with
             tests:
                - not_null
           - name: campgn_name
             description: name of specific campaign, note column name changed in staging
           - name: ads_cost
             description: cost of this ad, not cast as float64 in staging
           - name: impression
             description: number of impressions for this ad
           - name: click
             description: number of clicks from this ad
          tests:
           - unique:
              column_name: "(date_date || '-' || campaign_key)"
        - name: criteo
          identifier: raw_gz_criteo
          description: data from criteo for gz
          columns:
           - name: date_date
             description: date details
             tests:
                - not_null
           - name: paid_source
             description: source of ads
           - name: campaign_key
             description: key of specific campaign ad is associated with
             tests:
                - not_null
           - name: campgn_name
             description: name of specific campaign, note column name changed in staging
           - name: ads_cost
             description: cost of this ad, not cast as float64 in staging
           - name: impression
             description: number of impressions for this ad
           - name: click
             description: number of clicks from this ad
          tests:
           - unique:
              column_name: "(date_date || '-' || campaign_key)"
        - name: facebook
          identifier: raw_gz_facebook
          description: data from facebook for gz
          columns:
           - name: date_date
             description: date details
             tests:
                - not_null
           - name: paid_source
             description: source of ads
           - name: campaign_key
             description: key of specific campaign ad is associated with
             tests:
                - not_null
           - name: campgn_name
             description: name of specific campaign, note column name changed in staging
           - name: ads_cost
             description: cost of this ad, not cast as float64 in staging
           - name: impression
             description: number of impressions for this ad
           - name: click
             description: number of clicks from this ad
          tests:
           - unique:
              column_name: "(date_date || '-' || campaign_key)"
          
models:
              - name: int_sales_margin
                description: finding sales margin
                columns:
                - name: date_date
                  description: date of order
                  tests:
                    - not_null
                - name: orders_id
                  description: id of each order
                - name: revenue
                  description: revenue generated by order
                - name: quantity
                  description: number of items ordered
                - name: products_id
                  description: individual product id within orders
                - name: purchase_cost
                  description: quantity multiplied by purchase cost
                - name: margin
                  description: revenue minus purchase cost
                tests:
                  - unique:
                      column_name: "(orders_id || '-' || products_id)"
              - name: int_orders_margin
                description: finding order margin
                columns:
                - name: orders_id
                  description: id of each order
                  tests:
                    - unique
                    - not_null
                - name: date_date
                  description: date grouped
                  tests:
                    - not_null
                - name: revenue
                  description: sum of revenue
                - name: quantity
                  description: sum of quantity
                - name: purchase_cost
                  description: sum of purchase cost
                - name: margin
                  description: sum of margin
              - name: int_orders_operational
                description: finding operational margin
                columns:
                - name: orders_id
                  description: id of each order
                  tests:
                    - unique
                    - not_null
                - name: date_date
                  description: date grouped
                - name: revenue
                  description: sum of revenue
                - name: quantity
                  description: sum of quantity
                - name: purchase_cost
                  description: sum of purchase cost
                - name: margin
                  description: sum of margin
                - name: shipping_fee
                  description: cost paid by customer
                - name: logcost
                  description: logistics costs
                - name: operational_margin
                  description: margin plus shipping fee minus logcost minus ship_cost
              - name: finance_days
                description: key financial data aggregated by day
                columns:
                  - name: date_date
                    description: date for daily aggregations
                    # tests:
                    #   - unique
                    #   - not_null
                  - name: nb_transactions
                    description: number of transactions per day
                  - name: total_revenue
                    description: sum of daily revenue
                  - name: av_basket
                    description: average value of basket per day
                  - name: operational_margin
                    description: daily operational margin
                  - name: total_purchase_cost
                    description: total costs of products sold
                  - name: total_shipping_fees
                    description: total daily shipping fees income
                  - name: total_logcost
                    description: total daily logistics costs
                  - name: total_products_sold
                    description: total products sold per day
              - name: int_campaigns_day
                description: aggregated daily data on costs, impressions and clicks
                columns:
                  - name: date_date
                    description: date for each aggregated group
                    # tests: 
                    #   - unique
                    #   - not_null
                  - name: ads_cost
                    description: total costs of ads per day
                  - name: ads_impression
                    description: total number of impressions per day
                  - name: ads_clicks
                    description: total number of clicks per day
              - name: finance_campaigns_day
                description: Mart model including ads_margin calculation
                columns:
                  - name: finance_days.date_date
                    description: date for daily aggregations
                    tests:
                      - unique
                      - not_null
                  - name: ads_margin
                    description: margin calculated from operational margin minus ads cost
                  - name: av_basket
                    description: average value of basket per day
                  - name: operational_margin
                    description: daily operational margin
                  - name: nb_transactions
                    description: number of transactions per day
                  - name: total_revenue
                    description: sum of daily revenue
                  - name: total_purchase_cost
                    description: total costs of products sold
                  - name: total_shipping_fees
                    description: total daily shipping fees income
                  - name: total_logcost
                    description: total daily logistics costs
                  - name: total_products_sold
                    description: total products sold per day
                  - name: ads_cost
                    description: total ads costs per day
                  - name: ads_impression
                    description: number of impressions per day
                  - name: ads_clicks
                    description: number of clicks per day
