version: 2

sources: 
    - name: raw
      schema: gz_raw_data      
      description: Raw gz data from Le Wagon
      tables: 
        - name: sales 
          identifier: raw_gz_sales
          description: sales of Greenweez, one row per product_id found in each orders_id
          loaded_at_field: "CAST(date_date AS TIMESTAMP)"
          freshness:
            warn_after: {count: 90, period: day}
          columns:
            - name: date_date
              description: date of purchase
            - name: orders_id
              description: unique identifier for one order
            - name: products_id
              description: identifier for each product within an order
            - name: revenue
              description: revenue raised on each product
            - name: quantity
              description: number of each product purchased within this order
          tests:
            - unique:
                column_name: "(orders_id || '-' || pdt_id)"
        - name: product
          identifier: raw_gz_product
          description: products_id stored alongside purchase price for each of these products
          columns:
            - name: products_id
              description: unique identifier of each product, primary key
              tests:
                - unique  
                - not_null         
            - name: purchase_price
              description: price paid to acquire each individual product 
        - name: ship
          identifier: raw_gz_ship
          description: details of shipping fee(income) and log and ship costs against each orders_id
          columns:
            - name: orders_id
              description: unique identifier of each order, primary key
              tests:
                - unique
                - not_null
            - name: shipping_fee
              description: income paid for shipping
            - name: logCost
              description: logisitics costs in shipping order
            - name: ship_cost
              description: cost of shipping order
        - name: adwords
          identifier: raw_gz_adwords
          description: data from adwords for gz
          columns:
           - name: date_date,
           - name: paid_source,
           - name: campaign_key,
           - name: campgn_name,
           - name: ads_cost,
           - name: impression,
           - name: click
        - name: bing
          identifier: raw_gz_bing
          description: data from bing for gz
        - name: criteo
          identifier: raw_gz_criteo
          description: data from criteo for gz
        - name: facebook
          identifier: raw_gz_facebook
          description: data from facebook for gz
          
models:
              - name: int_sales_margin
                description: finding sales margin
                columns:
                - name: date_date
                  description: date of order
                  tests:
                    - not_null
                - name: orders_id
                  description: id of each order
                - name: revenue
                  description: revenue generated by order
                - name: quantity
                  description: number of items ordered
                - name: products_id
                  description: individual product id within orders
                - name: purchase_cost
                  description: quantity multiplied by purchase cost
                - name: margin
                  description: revenue minus purchase cost
                tests:
                  - unique:
                      column_name: "(orders_id || '-' || products_id)"
              - name: int_orders_margin
                description: finding order margin
                columns:
                - name: orders_id
                  description: id of each order
                  tests:
                    - unique
                    - not_null
                - name: date_date
                  description: date grouped
                  tests:
                    - not_null
                - name: revenue
                  description: sum of revenue
                - name: quantity
                  description: sum of quantity
                - name: purchase_cost
                  description: sum of purchase cost
                - name: margin
                  description: sum of margin
              - name: int_orders_operational
                description: finding operational margin
                columns:
                - name: orders_id
                  description: id of each order
                  tests:
                    - unique
                    - not_null
                - name: date_date
                  description: date grouped
                - name: revenue
                  description: sum of revenue
                - name: quantity
                  description: sum of quantity
                - name: purchase_cost
                  description: sum of purchase cost
                - name: margin
                  description: sum of margin
                - name: shipping_fee
                  description: cost paid by customer
                - name: logcost
                  description: logistics costs
                - name: operational_margin
                  description: margin plus shipping fee minus logcost minus ship_cost
